### ISSUE TITLE
A few questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [BasFaggingerAuer/tiny-game-engine#23]
Hi I have a few questions regarding this game engine:

1. Am I able to configure the game using C++?
2. Is this game engine kinda like [Toy](https://hugoam.github.io/toy-io/) game engine where the entire library and everything gets compiled into the game?
3. Is it released as stable?
4. Is this game engine as easy to learn as Unity3D?
5. Does it support gltf 3D object formats?

**Comment by BasFaggingerAuer** [comment]
@Joe23232,

With regards to you questions:

2., 3., 4. This engine is an unstable hobby project and is far more rudimentary than Toy/Unity/Unreal/... If you want to do serious game development I would strongly recommend **against** using tiny-game-engine, because you will have to do most things fully yourself in C++. If you want to learn more about OpenGL and creating your own 3D engine, then tiny-game-engine can be interesting.

1. You can use tiny-game-engine indeed as a static C++ library, see https://github.com/BasFaggingerAuer/tiny-game-engine/tree/master/moba for an example.
5. tiny-game-engine supports all 3D file formats supported by https://github.com/assimp/assimp. According to [this](https://github.com/assimp/assimp/blob/master/doc/Fileformats.md) list, gltf is likely supported.

Kind regards,

Bas

**Comment by Joe23232** [comment]
@BasFaggingerAuer 

Thank you very much :)
