### ISSUE TITLE
Renderables and textures cannot be freed

### ISSUE THREAD

**Issue by takenu** [BasFaggingerAuer/tiny-game-engine#5]
Renderables are added to the WorldRenderer via addWorldRenderable(). This adds a pointer to the Renderer which can then be used for rendering.

However, there does not seem to be a way to remove this Renderable, or free its allocated memory on the GPU. Additionally, the tiny-game-engine does not track usage of textures, and thus even if one could delete Renderables, the user would be forced to determine by himself whether deleting textures is safe.

I believe this issue needs a lot of work, and it's not going to be easy.

**Comment by BasFaggingerAuer** [comment]
Hmmm, I had envisioned resource management, e.g. for textures and models, to be separate from this engine. (Since this will depend strongly on the way resources are handled be the game.) Freeing renderables should be taken care of by the user, since the pointers will be required for in-game updates of, for example, mesh positions in a static mesh horde.

**Comment by takenu** [comment]
I agree, but even if resource management does not involve the engine, your current setup uses a list of renderables on which addWorldRenderable() uses push_back() to add new renderables which are then rendered every frame. But there is no function defined for removing renderables even if a user (such as myself) would want to do proper resource management.

However I did address this issue in pull request #6, so I suggest we look at the possibilities in more detail there.
